#!/bin/bash

DOTFILES=$(dirname $0 | xargs readlink -e)

for i in $(ls -A $DOTFILES/files/.vim/bundle/) ; do
    PLUGIN=${DOTFILES}/files/.vim/bundle/$i
    
    cd ${PLUGIN}
    if [ -e ${PLUGIN}/.git ] ; then
        echo Updating git repository for ${PLUGIN}
        git pull
    fi
    if [ -e ${PLUGIN}/.hg ] ; then
        echo Updating hg repository for ${PLUGIN}
        hg pull
        hg update
    fi
    if [ -e ${PLUGIN}/.svn ] ; then
        echo Updating svn repository for ${PLUGIN}
        svn update
    fi
done
