#!/usr/bin/env python

import sys
import os
import os.path
import shutil
import subprocess
import re

def main():
    hgsub = open(os.path.join(os.path.dirname(sys.argv[0]), ".hgsub"))
    hgsubline = re.compile("(\S+)\s*\=\s*(?:\[(git|hg|svn)\])?\s*(\S+)")
    for l in hgsub:
        m = hgsubline.match(l)
        if m != None:
            path = os.path.abspath(m.group(1))
            vcs = m.group(2)
            if vcs == None:
                vcs = "hg"
            url = m.group(3)
            
            print("%s = [%s] %s" % (path,vcs,url))

            parent = os.path.dirname(path)

            if not os.path.exists(parent):
                print("Creating directory: %s" % parent)
                os.makedirs(parent)

            if vcs == "git":
                if not os.path.exists(os.path.join(path, ".git")):
                    if os.path.exists(path):
                        print("Deleting invalid subrepository folder: %s" % path)
                        shutil.rmtree(path)
                    subprocess.call(["git", "clone", url], cwd=parent)
                else:
                    subprocess.call(["git", "pull"], cwd=path)

            elif vcs == "svn":
                if not os.path.exists(os.path.join(path, ".svn")):
                    if os.path.exists(path):
                        print("Deleting invalid subrepository folder: %s" % path)
                        shutil.rmtree(path)
                    subprocess.call(["svn", "checkout", url], cwd=parent)
                else:
                    subprocess.call(["svn", "update"], cwd=path)

            elif vcs == "hg":
                if not os.path.exists(os.path.join(path, ".hg")):
                    if os.path.exists(path):
                        print("Deleting invalid subrepository folder: %s" % path)
                        shutil.rmtree(path)
                    subprocess.call(["hg", "clone", url], cwd=parent)
                else:
                    subprocess.call(["hg", "pull", "-u"], cwd=path)

            else:
                print("Unknown repository type: %s" % vcs)
                pass

    
if __name__ == "__main__":
    main()
