#!/usr/bin/env python

import sys
import os
import urllib2

ROOT_DIR = os.path.abspath(os.path.dirname(sys.argv[0]))


def update_vim_plug():
    directory = os.path.join(ROOT_DIR, 'files', '.vim', 'autoload')
    if not os.path.exists(directory):
        os.makedirs(directory)
    url = 'https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
    with open(os.path.join(directory, 'plug.vim'), 'w') as f:
      f.write(urllib2.urlopen(url).read())


def main():
    update_vim_plug()


if __name__ == "__main__":
    main()

# vim:set sw=4 ts=4 expandtab:
